import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "security": "Security",
          "log_out": "Log Out",
          "block_user": "Block User",
          "invalid_message_template_id": "Invalid Message Template",
          "invalid_message_account_name": "Invalid Message Account Name",
          "phone_number": "Phone Number (with country code)",
          "terms": "Terms",
          "type_your_user_name":
              "Type your user name for get email for renew password",
          "university_name": "University Name",
          "invalid_message_account_type": "Invalid Message Account Type",
          "reason_text": "Reason Text",
          "there_is_no_chat": "There is no chat",
          "change_photo": "Change Photo",
          "complains": "Complains",
          "successfully_saved": "Successfully Saved",
          "message_templates": "Message Templates",
          "invalid_language_id": "Invalıd Language",
          "login": "Login",
          "type_a_message": "Type a message",
          "delete": "Delete",
          "user_email": "User Email",
          "culture_name": "Culture Name",
          "shuffle": "Shuffle",
          "number": "Number",
          "cancel": "Cancel",
          "skip_screen_sub_exp":
              "Freedom talk any person of your mother language",
          "there_is_no_data": "There is no data",
          "invalid_domain": "Invalid Domain",
          "token_count": "Token Count",
          "description": "Description",
          "send": "Send",
          "by_registring_accept_terms":
              "By signing up for the app, you accept our membership agreement.",
          "please_enter_correct_user_name": "Please enter correct user name",
          "language_name": "Language Name",
          "invalid_use_ssl": "Invalid Use SSL",
          "languages": "Languages",
          "i_want_to": "I want to",
          "message": "Message",
          "parameters_saved_successfully": "Parameters are saved successfully",
          "message_account_name": "Message Account Name",
          "is_gold": "Gold Member",
          "skip": "Skip",
          "send_email": "Send Email",
          "m_forgot_password_url": "Management Forgot Password URL",
          "invalid_email": "Invalid Email",
          "api_url": "API Url",
          "delete_chat": "Delete Chat",
          "created_date": "Created Date",
          "domain": "Domain",
          "success": "Success",
          "use_ssl": "Use SSL",
          "we_have_sent_email": "We`ve send an email for reset your password",
          "contact_us": "Contact Us",
          "complaint_user": "Complaint",
          "i_forgot_my_password": "I forgot my password",
          "main_photo": "Main profil",
          "privacy_policy": "Privacy Policy",
          "sign_up": "Sign Up",
          "statuses": "Statuses",
          "change_profile": "Change Profile",
          "gold_member": "Gold Member",
          "gold_member_requests": "Gold Member Requests",
          "invalid_message_account_id": "Invalid Message Account",
          "all": "All",
          "record_count": "Record",
          "complainted_user_id": "Complainted User Id",
          "body": "Body",
          "complainted_user_name": "Complainted User Name",
          "password": "Password",
          "old_password": "Old Password",
          "language": "Language",
          "port": "Port",
          "universities": "Universities",
          "guest": "Guest",
          "short_name": "Short Name",
          "search_ph": "Search...",
          "message_account_type": "Message Account Type",
          "content": "Content",
          "message_accounts": "Message Accounts",
          "show_orginal": "Show Orginal",
          "users": "Users",
          "blocked_members": "Blocked Members",
          "message_template_name": "Message Template Name",
          "missing_token": "Missing Token",
          "parameter": "Parameter",
          "m_forgot_password_message_template":
              "Management Forgot Password Template",
          "user_id": "User Id",
          "invalid_server": "Invalid Server",
          "about_us": "About Us",
          "active_users_desc":
              "There 303 people to talk, dont forget to shuffle",
          "u_forgot_password_url": "User Forgot Password URL",
          "email": "Email",
          "send_message": "Send Message",
          "value": "Value",
          "search_by_status": "Search by status",
          "sender": "Sender",
          "save": "Save",
          "translate_chat": "Translate Chat",
          "u_forgot_password_message_template": "User Forgot Password Template",
          "user_type_desc": "User Type",
          "start_chating": "Start Chating!",
          "logout": "Log Out",
          "complaint_user_id": "Complaint User Id",
          "add": "Add",
          "blogs": "Blogs",
          "please_add_photo":
              "You don`t  have any photo, please add photo for get more messages",
          "landing_text":
              "Open the Doors of an Honest and Sincere Chat on Chatinuni!",
          "subject": "Subject",
          "member": "Member",
          "detaıl": "Detail",
          "members": "Members",
          "server": "Server",
          "go_to_profile": "Go to profile",
          "is_blocked": "Blocked",
          "re_password": "Re-Password",
          "system_parameters": "System Parameters",
          "invalid_token": "Invalid Token",
          "user_name": "User Name",
          "message_account": "Message Account",
          "contact_phone_number": "Phone Number",
          "invalid_user_name": "Invalid User Name",
          "invalid_resource_id": "Invalid Resource",
          "user": "User",
          "complete_gold_member": "Complete Gold Member",
          "change_password": "Change Password",
          "gold_user_desc":
              "Want to receive messages from more people? Write your phone number and we`ll help you and get you more messages",
          "sign_up_successfull":
              "Sign up is successful you can start to use our system",
          "invalid_university_id": "Invalid University",
          "make_gold_user": "Make gold user",
          "message_template_type": "Message Template Type",
          "new_message": "New Message",
          "blocked": "Blocked",
          "university": "University",
          "static_translations": "Static Translations",
          "invalid_password": "Invalid Password",
          "translations": "Translations",
          "i_forgot_password": "I forgot password",
          "un_blocked": "Un Blocked",
          "choose_your_chat_language": "Choose your chat language",
          "search": "Search",
          "user_type": "User Type",
          "wrong_old_password": "Wrong Old Password",
          "system": "System",
          "complaint_user_name": "Complaint User Name",
          "settings": "Settings",
          "status": "Status",
          "invalid_user": "Invalid User",
          "new": "New",
          "invalid_sender": "Invalid Sender",
          "blog_list": "Blog List",
          "upload_photo": "Upload Photo",
          "skip_screen_exp": "Wellcome to ChatInUni",
          "u_new_user_message_template": "New User Message Template ",
          "field_required": "This field is required",
          "active_users": "Users",
          "no_data_found": "No Data Found"
        },
        'tr_TR': {
          "logout": "Log Out",
          "language_name": "Dil Adı",
          "please_enter_correct_user_name":
              "Lütfen kullanıcı adını kontrol edin",
          "invalid_university_id": "Geçersiz Üniversite",
          "server": "Sunucu",
          "un_blocked": "Bloklu Değil",
          "landing_text":
              "Chatinuni ile Gerçek ve Samimi Bir Sohbetin Kapılarını Arala!",
          "security": "Güvenlik",
          "new_message": "Yeni Message",
          "invalid_resource_id": "Geçersiz Kaynak",
          "active_users": "Kullanıcılar",
          "translate_chat": "Sohbeti Tercüme Et",
          "u_forgot_password_message_template":
              "Kullanıcı Şifremi Unuttum Şablonu",
          "static_translations": "Statik Çevrimler",
          "is_blocked": "Blok Durumu",
          "u_new_user_message_template": "Yeni Kullanıcı Mesaj Şablonu",
          "value": "Değer",
          "i_want_to": "",
          "sign_up_successfull":
              "Kayıt başarılı oldu sistemimizi kullanmaya başlayabilirsiniz",
          "search": "Ara",
          "invalid_message_account_type": "Geçersiz Mesaj Hesap Tipi",
          "log_out": "Oturumu Kapat",
          "system": "Sistem",
          "message_template_type": "Mesaj Template Tipi",
          "complaint_user": "Şikayet Et",
          "contact_phone_number": "Telefon Numarası",
          "i_forgot_password": "Şifremi unuttum",
          "please_add_photo":
              "Herhangi bir fotoğraf eklemediniz, daha fazla mesaj almak için lütfen fotoğraf ekleyin",
          "no_data_found": "Veri Bulunamadı",
          "upload_photo": "Fotoğraf Yükle",
          "message": "Mesaj",
          "description": "Açıklama",
          "save": "Kaydet",
          "message_account_type": "Mesaj Hesap Tipi",
          "complains": "Şikayetler",
          "email": "E-Posta",
          "record_count": "Kayıt",
          "re_password": "Tekrar Şifre",
          "status": "Durum",
          "port": "Port",
          "block_user": "Engelle",
          "we_have_sent_email":
              "Şifrenizi sıfırlamak için bir e-posta gönderdik",
          "sender": "Gönderen",
          "user_name": "Kullanıcı Adı",
          "invalid_message_account_name": "Geçersiz Mesaj Hesap Adı",
          "blocked": "Bloklu",
          "statuses": "Durumlar",
          "show_orginal": "Orjinali Göster",
          "there_is_no_data": "Herhangi bir veri bulunamadi",
          "number": "Numara",
          "gold_member_requests": "Gold Üye Talepleri",
          "choose_your_chat_language": "Sohbet dilinizi seçin",
          "blog_list": "Blog Listesi",
          "missing_token": "Token Kullanın",
          "subject": "Subject",
          "delete": "Sil",
          "wrong_old_password": "Yanlış Eski Şifre",
          "invalid_email": "Geçersiz E-Posta",
          "u_forgot_password_url": "Kullanıcı Şifremi Unuttum Şablonu",
          "invalid_password": "Geçersiz Şifre",
          "gold_user_desc":
              "Daha fazla kişiden mesaj almak ister misin? Telefon numaranı yaz, sana yardımcı olalım ve daha fazla mesaj almanı sağlayalım",
          "successfully_saved": "Başarıyla Kaydedildi",
          "shuffle": "Karıştır",
          "users": "Kullanıcı",
          "user_email": "Kullanıcı E-Posta",
          "domain": "Alan Adı",
          "user_id": "User Id",
          "member": "Üye",
          "change_password": "Şifre Değişikliği",
          "short_name": "Kısa Adı",
          "invalid_sender": "Geçersiz Gönderici",
          "phone_number": "Telefon Numarası (ülke kodu ile birlikte)",
          "user": "Kullanıcı",
          "invalid_message_account_id": "Geçersiz Mesaj Hesabı",
          "gold_member": "Gold Üye",
          "settings": "Ayarlar",
          "languages": "Diller",
          "there_is_no_chat": "Şuanda sohbet yok",
          "search_ph": "Ara...",
          "message_account_name": "Mesaj Hesap Adı",
          "complete_gold_member": "Gold Üyeliği Tamamla",
          "type_your_user_name":
              "Şifreni yenilemek için e-posta göndereceğiz, e-posta adresini yaz",
          "message_templates": "Mesaj Şablonları",
          "complaint_user_id": "Şikayet Eden Kullanıcı Id",
          "send": "Gönder",
          "invalid_language_id": "Geçersiz Dil",
          "active_users_desc": "Konuşacak 303 kişi var, karıştırmayı unutma",
          "change_profile": "Profili Düzenle",
          "message_account": "Mesaj Hesabı",
          "about_us": "Hakkımızda",
          "send_email": "E-Posta Gönder",
          "detaıl": "Detay",
          "invalid_server": "Geçersiz Server",
          "invalid_token": "Geçersiz Token",
          "invalid_user": "Geçersiz Kullanıcı",
          "university_name": "Üniversite Adı",
          "translations": "Çevrimler",
          "change_photo": "Fotoğraf Değiştir",
          "content": "İçerikler",
          "user_type_desc": "User Type",
          "field_required": "Bu alan zorunludur",
          "all": "Tümü",
          "message_accounts": "Mesaj Hesapları",
          "old_password": "Eski Şifre",
          "type_a_message": "Bir mesaj yazın",
          "terms": "Kullanım Şartları",
          "guest": "Misafir",
          "login": "Giriş",
          "by_registring_accept_terms":
              "Uygulamaya kaydolarak, üyelik sözleşmemizi kabul etmiş olursun.",
          "main_photo": "Ana Fotoğraf",
          "system_parameters": "Sistem Parametreleri",
          "university": "Üniversite",
          "blogs": "Blogs",
          "use_ssl": "SSL Kullan",
          "password": "Şifre",
          "new": "Yeni",
          "m_forgot_password_url": "Yonetim Şifremi Unuttum Linki",
          "skip_screen_sub_exp": "Herhangi bir kişiyle ana dilinizden konuşun",
          "members": "Üyeler",
          "skip": "Atla",
          "token_count": "Token Sayısı",
          "cancel": "Iptal",
          "culture_name": "Kültür Adı",
          "language": "Dil",
          "complainted_user_id": "Şikayet Edilen Kullanıcı Id",
          "add": "Ekle",
          "api_url": "API",
          "body": "İçerik",
          "message_template_name": "Mesaj Şablon Adı",
          "send_message": "Mesaj Gönder",
          "blocked_members": "Blocked Members",
          "complaint_user_name": "Şikayet Eden Kullanıcı Adı",
          "universities": "Üniversiteler",
          "user_type": "Kullanıcı Tipi",
          "contact_us": "Bize Ulaşın",
          "reason_text": "Sebep Metni",
          "invalid_message_template_id": "Geçersiz Mesaj Şablonu",
          "delete_chat": "Sohbeti Sil",
          "sign_up": "Kayıt Ol",
          "privacy_policy": "Gizlilik Sözleşmesi",
          "created_date": "Oluşturulma Tarihi",
          "go_to_profile": "Profile git",
          "skip_screen_exp": "ChatInUni`ye hoşgeldiniz",
          "invalid_use_ssl": "Geçersiz SSL Kullanımı",
          "success": "Success",
          "m_forgot_password_message_template":
              "Yonetim Şifremi Unuttum Şablonu",
          "complainted_user_name": "Şikayet Edilen Kullanıcı Adı",
          "search_by_status": "Duruma göre ara",
          "invalid_domain": "Geçersiz Alan Adı",
          "invalid_user_name": "Geçersiz Kullanıcı Adı",
          "parameter": "Parametre",
          "is_gold": "Gold Üye",
          "start_chating": "Şimdi Başla!",
          "make_gold_user": "Gold üye yap",
          "parameters_saved_successfully": "Parameters are saved successfully",
          "i_forgot_my_password": "I forgot my password"
        },
        'uk_UA': {
          "all": "All",
          "value": "Значення",
          "add": "Додати",
          "message_accounts": "Облікові записи повідомлень",
          "complainted_user_id": "Complainted User Id",
          "message_template_name": "Назва шаблону повідомлення",
          "domain": "Домену",
          "email": "Э-Почта",
          "blocked": "Blocked",
          "search": "Пошук",
          "reason_text": " Текст причини",
          "users": "Користувачів",
          "missing_token": "Відсутній Токен",
          "invalid_message_account_name":
              "Недійсне ім`я облікового запису повідомлення",
          "is_blocked": "Blocked",
          "message_account_name": "Назва облікового запису повідомлення",
          "delete": "Видалити",
          "languages": "Мови",
          "un_blocked": "Un Blocked",
          "search_by_status": "Пошук за статусом",
          "user_type": "User Type",
          "culture_name": "Назва культури",
          "i_forgot_my_password": "Я забув свій пароль",
          "wrong_old_password": "Неправильний Cтарий Пароль",
          "message_account_type": "Тип облікового запису повідомлення",
          "message_template_type": "Тип шаблону повідомлення",
          "gold_member": "Gold Member",
          "static_translations": "Статичні переклади",
          "token_count": "Token Count",
          "invalid_user": "Недійсний користувач",
          "language": "Мову",
          "invalid_message_account_id":
              "Недійсний обліковий запис повідомлення",
          "choose_your_chat_language": "Виберіть мову чату",
          "send_email": "Відправити лист",
          "terms": "Умови",
          "created_date": "Created Date",
          "log_out": "Вийти",
          "translations": "Переклади",
          "new": "Новий",
          "members": "Клієнти",
          "message_templates": "Шаблони повідомлень",
          "description": "Description",
          "message": "Повідомлення",
          "complete_gold_member": "Complete Gold Member",
          "m_forgot_password_message_template":
              "Керівництво забуло пароль шаблон",
          "system_parameters": "Системні параметри",
          "record_count": "Record",
          "port": "Порт",
          "status": "Статус",
          "successfully_saved": "Успішно збережено",
          "invalid_email": "Недійсна електронна адреса",
          "shuffle": "Перемішувати",
          "universities": "Університети",
          "invalid_message_account_type":
              "Недійсний тип облікового запису повідомлення",
          "start_chating": "Почніть спілкуватися!",
          "send_message": "Відправити повідомлення",
          "login": "Вхід",
          "password": "Пароль",
          "user_id": "User Id",
          "privacy_policy": "Політика конфіденційності",
          "i_forgot_password": "Я забув пароль",
          "server": "Сервер",
          "invalid_resource_id": "Недійсний ресурс",
          "parameter": "Параметр",
          "complaint_user_name": "Complaint User Name",
          "delete_chat": "Видалити чат",
          "invalid_sender": "Недійсний відправник",
          "new_message": "Нове повідомлення",
          "member": "Клієнт",
          "type_your_user_name":
              "Введіть своє ім’я користувача для отримання електронної пошти для відновлення пароля",
          "user": "Користувач",
          "there_is_no_chat": "Немає чату",
          "invalid_password": "Недійсний пароль",
          "search_ph": "Пошук",
          "university": "Університет",
          "blog_list": "Список Блогів",
          "invalid_language_id": "Недійсна мова",
          "statuses": "Статуси",
          "landing_text":
              "Відкрийте двері справжнього та щирого спілкування з Chatinuni!",
          "body": "Body",
          "no_data_found": "Даних не знайдено",
          "old_password": "Старий Пароль",
          "number": "Номер",
          "complains": "Cкаржиться",
          "user_email": "User Email",
          "please_add_photo":
              "У вас немає фото, будь ласка, додайте фото, щоб отримувати більше повідомлень",
          "gold_member_requests": "Gold Member Requests",
          "parameters_saved_successfully": "Параметри успішно збережено",
          "gold_user_desc":
              "Хочете отримувати повідомлення від більшої кількості людей? Напишіть свій номер телефону, і ми допоможемо вам і отримаємо більше повідомлень",
          "sign_up_successfull":
              "Реєстрація пройшла успішно, ви можете почати користуватися нашою системою",
          "user_name": "Ім`я користувача",
          "u_forgot_password_message_template":
              "Шаблон користувача забув пароль",
          "complaint_user": "Подати скаргу",
          "active_users_desc":
              "Є 303 людини, щоб поговорити, не забудьте перетасувати",
          "contact_phone_number": "Телефонний номер",
          "active_users": "Активні",
          "u_forgot_password_url": "Користувач забув пароль URL",
          "cancel": "Скасувати",
          "blogs": "Блоги",
          "use_ssl": "Використовуйте SSL",
          "go_to_profile": "Перейти в профіль",
          "user_type_desc": "User Type",
          "contact_us": "Зв`яжіться з нами",
          "skip_screen_exp": "Ласкаво просимо до ChatInUni",
          "university_name": "Назва університету",
          "complaint_user_id": "Complaint User Id",
          "phone_number": "Номер телефону (з кодом країни)",
          "system": "Система",
          "success": "Успіх",
          "subject": "Тема",
          "invalid_university_id": "Недійсний університет",
          "by_registring_accept_terms":
              "Реєструючись у програмі, ви приймаєте нашу угоду про членство.",
          "type_a_message": "Введіть повідомлення",
          "re_password": "Re Password",
          "main_photo": " Основний профіль",
          "security": "Безпека",
          "language_name": "Назва мови",
          "invalid_token": "Неприпустимий маркер",
          "blocked_members": "Заблокованих Учасників",
          "send": "Відправити",
          "invalid_server": "Недійсний сервер",
          "invalid_message_template_id": "Недійсний шаблон повідомлення",
          "guest": "Guest",
          "invalid_user_name": "Невірне ім`я користувача",
          "we_have_sent_email":
              "Ми надіслали електронний лист для зміни вашого пароля",
          "logout": "Вийти",
          "sender": "Відправник",
          "content": "Зміст",
          "show_orginal": "Показати оригінал",
          "api_url": "API Url",
          "detaıl": "Деталь",
          "u_new_user_message_template":
              "Новий шаблон повідомлення користувача",
          "invalid_use_ssl": "Недійсне використання SSL",
          "m_forgot_password_url": "Керівництво забуло пароль URL",
          "make_gold_user": "Золотий користувач",
          "sign_up": "Реєстрація",
          "translate_chat": "Перекласти Чат",
          "change_profile": " Змінити Профіль",
          "about_us": "О нас",
          "invalid_domain": "Недійсний домен",
          "skip": "Пропустити",
          "change_photo": "Змінити фотографію",
          "there_is_no_data": "Даних немає",
          "change_password": "Змінити Пароль",
          "block_user": "Заблокувати",
          "complainted_user_name": "Complainted User Name",
          "short_name": "Коротке ім`я",
          "field_required": "Це поле є обов`язковим",
          "is_gold": "Gold Member",
          "skip_screen_sub_exp":
              "Свобода розмовляйте з будь-якою людиною рідною мовою",
          "please_enter_correct_user_name":
              "Будь ласка, введіть правильне ім`я користувача",
          "upload_photo": "Завантажити фото",
          "i_want_to": "Я хочу",
          "save": "Зберегти",
          "message_account": "Обліковий запис повідомлень",
          "settings": "Налаштування"
        }
      };
}
